Football/Models/Positions/AddPositionFormModel.cs
namespace Football.Models.Positions
{
    using System.ComponentModel.DataAnnotations;

    using static Football.Infrastructure.Data.DataConstants.Position;

    public class AddPositionFormModel
    {
        [Required]
        [StringLength(PositionNameMaxLength)]
        public string? Name { get; set; }
    }
}

Football/Controllers/PositionsController.cs
namespace Football.Controllers
{
    using Football.Core.Constants;
    using Football.Core.Contracts;
    using Football.Core.Models.Positions;
    using Football.Extensions;
    using Football.Infrastructure.Data;
    using Football.Infrastructure.Data.Models;
    using Football.Models.Positions;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    public class PositionsController : Controller
    {
        private readonly FootballDbContext data;
        private readonly IManagerService managers;

        public PositionsController(
            FootballDbContext _data,
            IManagerService _мanagers)
        {
            this.data = _data;
            this.managers = _мanagers;
        }

        [Authorize]
        public async Task<IActionResult> Add()
        {
            if (!this.managers.IsManager(this.User.Id()))
            {
                return RedirectToAction(nameof(ManagersController.Become),
                    "Managers");
            }

            return View(new PositionFormModel
            {
            });
        }

        [HttpPost]
        public IActionResult Add(AddPositionFormModel position)
        {
            if (!ModelState.IsValid)
            {
                return View(position);
            }

            var positionData = new Position
            {
                Name = position.Name,
            };

            this.data.Positions.Add(positionData);

            this.data.SaveChanges();

            ViewData[MessageConstant.SuccessMessage] = "Успешен запис";

            return View();
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

Football/Views/Positions/Add.cshtml
@model PositionFormModel

@{
    ViewData["Title"] = "Добавяне на позиция";
}

<div class="container">
    <div class="row">
        <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
            <h2 class="heading-margin text-center">@ViewBag.Title</h2>
            <form method="post" enctype="multipart/form-data">
                <div class="form-group">
                    <label asp-for="Name"></label>
                    <input asp-for="Name" class="form-control" placeholder="вратар, защитник, нападател, и т.н...">
                    <span asp-validation-for="Name" class="small text-danger"></span>
                </div>
                <input class="btn btn-primary" type="submit" value="Save" />
               @* <input class="btn btn-warning" type="submit" value="Edit" />
                 <a asp-controller="Positions" asp-action="Delete" asp-route-id="Id" class="btn btn-danger">Delete</a>*@
            </form>
        </div>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}