Football/Models/Stadiums/AddStadiumFormModel.cs
namespace Football.Models.Stadiums
{
    using System.ComponentModel.DataAnnotations;

    using static Football.Infrastructure.Data.DataConstants.Stadium;

    public class AddStadiumFormModel
    {

        [Display(Name = "City Name")]
        [Required]
        [StringLength(StadiumNameMaxLength, MinimumLength = StadiumNameMinLength, ErrorMessage = "Minimum: {2}, Maximum: {1}")]
        public string Name { get; set; }

        [Required]
        public string Image { get; set; }

        public int Capacity { get; set; }

        [Display(Name = "Описание")]
        [Required()]
        [StringLength(int.MaxValue,
            MinimumLength = StadiumDescriptionMinLength,
            ErrorMessage = "The field Description must be a string with a minimum length of {2}.")]
        public string Description { get; init; }

        [Display(Name = "City Address")]
        [Required]
        [StringLength(StadiumAddressMaxLength, MinimumLength = StadiumAddressMinLength, ErrorMessage = "Minimum: {2}, Maximum: {1}")]
        public string Address { get; set; }

        [Display(Name = "City")]
        public Guid CityId { get; init; }

        public IEnumerable<StadiumCitiesViewModel> Cities { get; set; }
    }
}

Football/Models/Stadiums/StadiumCitiesViewModel.cs
namespace Football.Models.Stadiums
{
    public class StadiumCitiesViewModel
    {
        public Guid Id { get; set; }

        public string? Name { get; set; }
    }
}

Football/Models/Stadiums/StadiumListingViewModel.cs
namespace Football.Models.Stadiums
{
    public class StadiumListingViewModel
    {
        public Guid Id { get; set; }

        public string Name { get; set; }

        public string Image { get; set; }

        public string Decription { get; set; }

        public int Capacity { get; set; }

        public string Address { get; set; }

        public string City { get; set; }
    }
}

Football/Areas/Admin/Controllers/StadiumsController.cs
namespace Football.Areas.Admin.Controllers
{
    using Football.Core.Contracts;
    using Microsoft.AspNetCore.Mvc;

    public class StadiumsController : BaseController
    {
        private readonly IStadiumService stadiums;

        public StadiumsController(IStadiumService _stadiums)
        {
            this.stadiums = _stadiums;
        }

        public IActionResult All()
        {
            var stadiums =
                this.stadiums
                .All(publicOnly: false)
                .Stadiums;

            return View(stadiums);
        }
        public IActionResult ChangeVisibility(Guid id)
        {
            this.stadiums.ChangeVisibility(id);

            return RedirectToAction(nameof(All));
        }
    }
}

Football/Controllers/StadiumsController.cs
namespace Football.Controllers
{
    using Football.Core.Contracts;
    using Football.Core.Models.Stadiums;
    using Football.Extensions;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    using static WebConstants;
    public class StadiumsController : Controller
    {
        private readonly IStadiumService stadiums;
        private readonly IManagerService managers;

        private readonly IWebHostEnvironment webHostEnvironment;

        public StadiumsController(
            IStadiumService _stadiums,
            IManagerService _managers,
            IWebHostEnvironment _webHostEnvironment)
        {
            this.stadiums = _stadiums;
            this.managers = _managers;
            this.webHostEnvironment = _webHostEnvironment;
        }

        public IActionResult All([FromQuery] AllStadiumsQueryModel query)
        {
            var queryResult = this.stadiums.All(
                query.Name,
                query.SearchTerm,
                query.Sorting,
                query.CurrentPage,
                AllStadiumsQueryModel.StadiumsPerPage);

            var stadiumNames = this.stadiums.AllNames();

            query.Names = stadiumNames;
            query.TotalStadiums = queryResult.TotalStadiums;
            query.Stadiums = queryResult.Stadiums;

            return View(query);
        }

        [Authorize]
        public IActionResult Mine()
        {
            var myStadiums = this.stadiums.ByUser(this.User.Id());

            return View(myStadiums);
        }

        public IActionResult Details(Guid id, string information)
        {
            var stadium = this.stadiums.Details(id);

            if (information != stadium.GetInformation())
            {
                return BadRequest();
            }

            return View(stadium);
        }

        [Authorize]
        public IActionResult Add()
        {
            if (!this.managers.IsManager(this.User.Id()))
            {
                return RedirectToAction(nameof(ManagersController.Become), "Managers");
            }

            return View(new StadiumFormModel
            {
                Cities = this.stadiums.AllCities()
            });
        }

        [HttpPost]
        [Authorize]
        public IActionResult Add(StadiumFormModel stadium)
        {
            var managerId = this.managers.IdByUser(this.User.Id());

            if (managerId.Equals(Guid.Empty))
            {
                return RedirectToAction(nameof(ManagersController.Become), "Managers");
            }

            if (!this.stadiums.CityExists(stadium.CityId))
            {
                this.ModelState.AddModelError(nameof(stadium.CityId), "City does not exist.");
            }

            if (ModelState.IsValid)
            {
                stadium.Cities = this.stadiums.AllCities();

                return View(stadium);
            }

            string stringFileName = UploadFile(stadium);

            var stadiumId = this.stadiums.Create(
                  stadium.Name,
                  stringFileName,
                  stadium.Description,
                  stadium.Capacity,
                  stadium.Address,
                  stadium.CityId,
                  managerId);


            TempData[GlobalMessageKey] = "You Stadium was added and is awaiting for approval!";

            return RedirectToAction(nameof(Details), new { id = stadiumId, information = stadium.GetInformation() });
        }

        [Authorize]
        public IActionResult Edit(Guid id)
        {
            var userId = this.User.Id();

            if (!this.managers.IsManager(userId) && !User.IsAdmin())
            {
                return RedirectToAction(nameof(ManagersController.Become), "Managers");
            }

            var stadium = this.stadiums.Details(id);

            if (stadium.UserId != userId && !User.IsAdmin())
            {
                return Unauthorized();
            }

            return View(new StadiumFormModel
            {
                Name = stadium.Name,
                //Image = stadium.Image,
                Description = stadium.Description,
                Capacity = stadium.Capacity,
                Address = stadium.Address,
                CityId = stadium.CityId,
                Cities = this.stadiums.AllCities()
            });
        }

        [HttpPost]
        [Authorize]
        public IActionResult Edit(Guid id, StadiumFormModel stadium)
        {
            var managerId = this.managers.IdByUser(
                this.User.Id());

            string stringFileName = UploadFile(stadium);

            if (managerId.Equals(Guid.Empty) && !User.IsAdmin())
            {
                return RedirectToAction(nameof(ManagersController.Become
                    ), "Managers");
            }

            if (!this.stadiums.CityExists(stadium.CityId))
            {
                this.ModelState.AddModelError(nameof(stadium.CityId), "City does not exist.");
            }

            if (ModelState.IsValid)
            {
                stadium.Cities = this.stadiums.AllCities();

                return View(stadium);
            }

            if (!this.stadiums.IsByManager(id, managerId) && !User.IsAdmin())
            {
                return BadRequest();
            }

            var edited = this.stadiums.Edit(
                   id,
                   stadium.Name,
                   stringFileName,
                   stadium.Description,
                   stadium.Capacity,
                   stadium.Address,
                   stadium.CityId,
                   this.User.IsAdmin());

            if (!edited)
            {
                return BadRequest();
            }

            TempData[GlobalMessageKey] = $"You Team was edited {(this.User.IsAdmin() ? string.Empty : " and is await for approval")}!";

            return RedirectToAction(nameof(Details), new { id, information = stadium.GetInformation() });
        }


        [HttpGet]
        public IActionResult Delete(Guid id)
        {
            if (id.Equals(Guid.Empty))
            {
                return NotFound();
            }

            var delete = this.stadiums.Delete(id);

            TempData[DangerMessageKey] = $"You Stadium was deleted!";

            return RedirectToAction(nameof(All));
        }

        private string UploadFile(StadiumFormModel model)
        {
            string fileName = null;
            if (model.Image != null)
            {
                string uploadDir = Path.Combine(webHostEnvironment.WebRootPath, "img");
                fileName = Guid.NewGuid().ToString() + "-" + model.Image.FileName;
                string filePath = Path.Combine(uploadDir, fileName);

                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    model.Image.CopyTo(fileStream);
                }
            }

            return fileName;
        }
    }
}

Football/Views/Stadiums/Add.cshtml
@model StadiumFormModel

@{
    ViewData["Title"] = "Добавяне на стадион";
}

<partial name="_StadiumFormPartial" model="@Model"/>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Football/Views/Stadiums/All.cshtml
@model AllStadiumsQueryModel

@{
    ViewData["Title"] = "Всички стадиони";
}

<form method="get">
    <div class="row">
        <div class="form-group col-md-4">
            <div class="form-group">
                <label asp-for="Name"></label>
                <select asp-for="Name" class="form-control">
                    <option value="">Всички</option>

                    @foreach (var stadium in Model.Names)
                    {
                        <option value="@stadium">@stadium</option>
                    }
                </select>
            </div>
        </div>

        <div class="form-group col-md-4">
            <label asp-for="SearchTerm"></label>
            <input asp-for="SearchTerm" class="form-control" placeholder="Георги Аспарухов, Българска армия и т. н....">
        </div>

        <div class="form-group col-md-4">
            <div class="form-group">
                <label asp-for="Sorting"></label>
                <select asp-for="Sorting" class="form-control">
                    <option value="0" selected>Име</option>
                    <option value="1" selected>Капацитет</option>
                    @*<option value="2" selected>Position</option>
                        <option value="3" selected>Description</option>*@
                </select>
            </div>
        </div>
    </div>
</form>

@{
    var previousPage = Model.CurrentPage - 1;
    if (previousPage < 1)
    {
        previousPage = 1;
    }

    var maxPage = Math.Ceiling((double)Model.TotalStadiums / AllStadiumsQueryModel.StadiumsPerPage);
}

<div class="row mb-5">
    <div class="col-md-6">
        <a class="btn btn-primary @(Model.CurrentPage == 1 ? "disabled" : string.Empty)"
           asp-controller="Stadiums"
           asp-action="All"
           asp-route-currentPage="@previousPage"
           asp-route-team="@Model.Name"
           asp-route-searchTerm="@Model.SearchTerm"
           asp-route-sorting="@((int)Model.Sorting)"><<</a>
    </div>
    <div class="col-md-6">
        <a class="btn btn-primary float-right @(Model.CurrentPage == maxPage ? "disabled" : string.Empty)"
           asp-controller="Stadiums"
           asp-action="All"
           asp-route-currentPage="@(Model.CurrentPage + 1)"
           asp-route-team="@Model.Name"
           asp-route-searchTerm="@Model.SearchTerm"
           asp-route-sorting="@((int)Model.Sorting)">>></a>
    </div>
    <br />
    <br />

        @if (!Model.Stadiums.Any())
    {
        <h2 class="text-center">Няма намерени стадиони по зададените критерии!</h2>
    }

    <partial name="_StadiumsPartial" model="@Model.Stadiums" />

Football/Views/Stadiums/Details.cshtml
@model StadiumDetailsServiceModel

@{
    ViewData["Title"] = "Стадион";
}


<div class="col-md-6 offset-3">

    <img src="~/img/@Model.Image" width="300" height="200>

"></h2>
    </div>
<br />


<div class="col-md-6 offset-3">

    <td><h3></h3>Стадион:</td>
              <h2 class="list-group-item"> @Model.Name</h2>
    <td><h3></h3>Капацитет:</td>
                <h2 class="list-group-item"> @Model.Capacity</h2>
   <td><h3></h3>Адрес:</td>
                <h2 class="list-group-item"> @Model.Address</h2>
    <td><h3></h3>Описание:</td>
                <h2 class="list-group-item"> @Model.Description</h2>
</div>

Football/Views/Stadiums/Edit.cshtml
@model StadiumFormModel

@{
    ViewBag.Title = "Редактиране на стадион";
}

<partial name="_StadiumFormPartial" model="@Model" />

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Football/Views/Stadiums/Mine.cshtml
@model IEnumerable<StadiumServiceModel>

@{
    ViewBag.Title = "Моите стадиони";
    ViewBag.AllowStadiumEdit = true;
}

@if (!Model.Any())
{
    <h2 class="text-center">Все още нямате Стадиони!</h2>
}

 <partial name="_StadiumsPartial" model="@Model" />

Football/Views/Stadiums/_StadiumFormPartial.cshtml
@model StadiumFormModel

<div class="container">
    <div class="row">
        <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
            <h2 class="heading-margin text-center">@ViewBag.Title</h2>
            <form method="post" enctype="multipart/form-data">
                <div class="form-group">
                    <label asp-for="Name"></label>
                    <input asp-for="Name" class="form-control" placeholder="Ивайло, Виваком Арена, и т.н....">
                    <span asp-validation-for="Name" class="small text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Image"></label>
                    <input asp-for="Image" class="form-control" placeholder="">
                    <span asp-validation-for="Image" class="small text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Capacity"></label>
                    <input asp-for="Capacity" class="form-control">
                    <span asp-validation-for="Capacity" class="small text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Address"></label>
                    <input asp-for="Address" class="form-control" placeholder="ул.Иван Вазов и т.н.">
                    <span asp-validation-for="Capacity" class="small text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Description"></label>
                    <textarea asp-for="Description" rows="4" class="form-control" placeholder="Стадион с много футболна история"></textarea>
                    <span asp-validation-for="Description" class="small text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="CityId"></label>
                    <select asp-for="CityId" class="form-control">
                        @foreach (var city in Model.Cities)
                        {
                            <option value="@city.Id">@city.Name</option>
                        }
                    </select>
                    <span asp-validation-for="CityId" class="small text-danger"></span>
                </div>
                <br />

                @* <input type="file" name="Image" />*@
                <input class="btn btn-primary" type="submit" value="Save" />
            </form>
            <br />
        </div>
    </div>
</div>

Football/Views/Stadiums/_StadiumsPartial.cshtml
@model IEnumerable<StadiumServiceModel>

<div class="row">

    @foreach (var stadium in Model)
    {
        <div class="col-md-4">
            <div class="card mb-3">
                <img src="~/img/@stadium.Image" alt="@stadium.Name @stadium.Address @stadium.Capacity)">
                <div class="card-body text-center">
                    <h5 class="card-title text-center">@stadium.Name  @stadium.Address @stadium.Capacity</h5>
                    <br />
                    <a asp-controller="Stadiums" asp-action="Details" asp-route-id=@stadium.Id  asp-route-information="@stadium.GetInformation()" class="btn btn-primary">View</a>
                    @if (ViewBag.AllowStadiumEdit == true || User.IsAdmin())
                    {
                        <a asp-controller="Stadiums" asp-action="Edit" asp-route-id="@stadium.Id" class="btn btn-warning">Edit</a>
                        <a asp-controller="Stadiums" asp-action="Delete" asp-route-id="@stadium.Id" class="btn btn-danger">Delete</a>
                    }
                </div>
            </div>
        </div>
    }
</div>