Football/Controllers/CitiesController.cs
namespace Football.Controllers
{
    using Football.Core.Contracts;
    using Football.Core.Models.Cities;
    using Football.Extensions;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    using static WebConstants;
    public class CitiesController : Controller
    {
        private readonly IManagerService managers;
        private readonly ICityService cities;

        private readonly IWebHostEnvironment webHostEnvironment;

        public CitiesController(
            IManagerService _managers,
            ICityService _cities,
            IWebHostEnvironment _webHostEnvironment)
        {
            this.managers = _managers;
            this.cities = _cities;
            this.webHostEnvironment = _webHostEnvironment;
        }

        public IActionResult All([FromQuery]
        AllCityQueryModel query)
        {
            var queryResult = this.cities.All(
                query.Name,
                query.SearchTerm,
                query.Sorting,
                query.CurrentPage,
                AllCityQueryModel.CityPerPage);


            var cityNames = this.cities.AllNames();

            query.Names = cityNames;
            query.TotalCities = queryResult.TotalCities;
            query.Cities = queryResult.Cities;

            return View(query);
        }

        [Authorize]
        public IActionResult Mine()
        {
            var myCities = this.cities.ByUser(this.User.Id());

            return View(myCities);
        }

        public IActionResult Details(Guid id, string information)
        {
            var city = this.cities.Details(id);

            if (information != city.GetInformation())
            {
                return BadRequest();
            }

            return View(city);
        }

        [Authorize]
        public IActionResult Add()
        {
            if (!this.managers.IsManager(this.User.Id()))
            {
                return RedirectToAction(nameof(ManagersController.Become),
                    "Managers");
            }
            return View(new CityFormModel
            {
                Teams = this.cities.AllTeams()
            });
        }


        [HttpPost]
        [Authorize]
        public IActionResult Add(CityFormModel city)
        {
            var managerId = this.managers.IdByUser(this.User.Id());

            if (managerId.Equals(Guid.Empty))
            {
                return RedirectToAction(nameof(ManagersController.Become), "Managers");
            }

            if (!this.cities.TeamExists(city.TeamId))
            {
                this.ModelState.AddModelError(nameof(city.TeamId),
                    "City does not exist.");
            }

            if (ModelState.IsValid)
            {
                city.Teams = this.cities.AllTeams();

                return View(city);
            }

            string stringFileName = UploadFile(city);

            var cityId = this.cities.Create(
                  city.Name,
                  city.PostCode,
                  stringFileName,
                  city.Description,
                  city.TeamId);

            TempData[GlobalMessageKey] = "You Team was added and is awaiting for approval!";

            return RedirectToAction(nameof(Details), new { id = cityId, information = city.GetInformation() });

        }

        [Authorize]
        public IActionResult Edit(Guid id)
        {
            var userId = this.User.Id();

            if (!this.managers.IsManager(userId) && !User.IsAdmin())
            {
                return RedirectToAction(nameof(ManagersController.Become),
                    "Managers");
            }

            var city = this.cities.Details(id);

            if (city.UserId != userId && !User.IsAdmin())
            {
                return Unauthorized();
            }

            return View(new CityFormModel
            {
                Name = city.Name,
                PostCode = city.PostCode,
                //Image = city.Image,
                Description = city.Description,
                TeamId = city.TeamId,
                Teams = this.cities.AllTeams(),
            });
        }

        [HttpPost]
        [Authorize]
        public IActionResult Edit(Guid id, CityFormModel city)
        {
            var managerId = this.managers.IdByUser(
                this.User.Id());

            string strinfFileName = UploadFile(city);

            if (managerId.Equals(Guid.Empty) && !User.IsAdmin())
            {
                return RedirectToAction(nameof(ManagersController.Become),
                    "Managers");
            }

            if (!this.cities.TeamExists(city.TeamId))
            {
                this.ModelState.AddModelError(nameof(city.TeamId),
                    "Team does not exist.");
            }

            if (ModelState.IsValid)
            {
                city.Teams = this.cities.AllTeams();

                return View(city);
            }

            if (!this.cities.IsByManager(id, managerId) && !User.IsAdmin())
            {
                return BadRequest();
            }

            var edited = this.cities.Edit(
                  id,
                  city.Name,
                  city.PostCode,
                  strinfFileName,
                  city.Description,
                  city.TeamId,
                  this.User.IsAdmin());

            if (!edited)
            {
                return BadRequest();
            }

            TempData[GlobalMessageKey] = $"You Team was edited {(this.User.IsAdmin() ? string.Empty : " and is await for approval")}!";

            return RedirectToAction(nameof(Details), new { id, information = city.GetInformation() });
        }


        [HttpGet]
        public IActionResult Delete(Guid id)
        {
            if (id.Equals(Guid.Empty))
            {
                return NotFound();
            }

            var delete = this.cities.Delete(id);

            TempData[DangerMessageKey] = $"You City was deleted!";

            return RedirectToAction(nameof(All));
        }

        private string UploadFile(CityFormModel model)
        {
            string fileName = null;
            if (model.Image != null)
            {
                string uploadDir = Path.Combine(webHostEnvironment.WebRootPath, "img");
                fileName = Guid.NewGuid().ToString() + "-" + model.Image.FileName;
                string filePath = Path.Combine(uploadDir, fileName);

                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    model.Image.CopyTo(fileStream);
                }
            }

            return fileName;
        }
    }
}

Football/Controllers/GeoController.cs
namespace Football.Controllers
{
    using Football.Models.GeoLocation;
    using Microsoft.AspNetCore.Mvc;
    using Newtonsoft.Json;

    public class GeoController : Controller
    {
        public async Task<ActionResult> Details()
        {
            GeoLocationViewModel model = new GeoLocationViewModel();
            GeoHelper geoHelper = new GeoHelper();
            var result = await geoHelper.GetGeoInfo();
            model = JsonConvert.DeserializeObject<GeoLocationViewModel>(result);
            //TempData["GeoCode"] = result;

            return View(model);
        }
    }
}

Football/Controllers/TeamsController.cs
namespace Football.Controllers
{
    using Football.Core.Contracts;
    using Football.Core.Models.Teams;
    using Football.Extensions;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    using static WebConstants;
    public class TeamsController : Controller
    {
        public readonly ITeamService teams;
        private readonly IManagerService managers;

        private readonly IWebHostEnvironment webHostEnvironment;

        public TeamsController(
            ITeamService _teams,
            IManagerService _managers,
            IWebHostEnvironment _webHostEnvironment)
        {
            this.teams = _teams;
            this.managers = _managers;
            this.webHostEnvironment = _webHostEnvironment;
        }

        public IActionResult All([FromQuery]
               AllTeamQueryModel query)
        {
            var queryResult = this.teams.All(
                query.Team,
                query.SearchTerm,
                query.Sorting,
                query.CurrentPage,
                AllTeamQueryModel.TeamPerPage);

            var teamsPlayers = this.teams.AllPlayers();

            //TODO
            query.TeamCities = teamsPlayers;
            query.TotalTeams = queryResult.TotalTeams;
            query.Teams = queryResult.Teams;

            return View(query);
        }

        [Authorize]
        public IActionResult Mine()
        {
            var myTeams = this.teams.ByUser(this.User.Id());

            return View(myTeams);
        }

        public IActionResult Details(Guid id, string information)
        {
            var team = this.teams.Details(id);

            if (information != team.GetInformation())
            {
                return BadRequest();
            }

            return View(team);
        }


        [Authorize]
        public IActionResult Add()
        {
            if (!this.managers.IsManager(this.User.Id()))
            {
                return RedirectToAction(nameof(ManagersController.Become),
                    "Managers");
            }

            return View(new TeamFormModel
            {
                //TODO
                Players = this.teams.AllTeams()
            });
        }

        [HttpPost]
        [Authorize]
        public IActionResult Add(TeamFormModel team)
        {
            var managerId = this.managers.IdByUser(this.User.Id());

            if (managerId.Equals(Guid.Empty))
            {
                return RedirectToAction(nameof(ManagersController.Become),
                    "Managers");
            }

            if (!this.teams.PlayerExists(team.PlayerId))
            {
                this.ModelState.AddModelError(nameof(team.PlayerId),
                    "Team does not exist.");
            }

            if (ModelState.IsValid)
            {
                //team.Players = this.teams.AllPlayers();

                return View(team);
            }

            string stringFileName = UploadFile(team);

            var teamId = this.teams.Create(
                 team.Name,
                 stringFileName,
                 team.WebSite,
                 team.LogoUrl,
                 team.HomeKit,
                 team.AwayKit,
                 team.NickName,
                 team.Description,
                 team.Address,
                 team.HeadCoach,
                 team.Champion,
                 team.Cup,
                 team.Win,
                 team.Defeats,
                 team.PlayerId,
                 managerId);

            TempData[GlobalMessageKey] = "You Team was added and is awaiting for approval!";

            return RedirectToAction(nameof(Details), new { id = teamId, information = team.GetInformation() });
        }

        [Authorize]
        public IActionResult Edit(Guid id)
        {
            var userId = this.User.Id();

            if (!this.managers.IsManager(userId) && !User.IsAdmin())
            {
                return RedirectToAction(nameof(ManagersController.Become),
                    "Managers");
            }

            var team = this.teams.Details(id);

            if (team.UserId != userId && !User.IsAdmin())
            {
                return Unauthorized();
            }

            return View(new TeamFormModel
            {
                Name = team.Name,
                //Image = team.Image,
                WebSite = team.WebSite,
                LogoUrl = team.LogoUrl,
                HomeKit = team.HomeKit,
                AwayKit = team.AwayKit,
                NickName = team.NickName,
                Description = team.Description,
                Address = team.Address,
                HeadCoach = team.HeadCoach,
                Champion = team.Champion,
                Cup = team.Cup,
                Win = team.Win,
                Defeats = team.Defeats,
                PlayerId = team.PlayerId,
                Players = this.teams.AllTeams()
            });
        }

        [HttpPost]
        [Authorize]
        public IActionResult Edit(Guid id, TeamFormModel team)
        {
            var managerId = this.managers.IdByUser(this.User.Id());

            string stringFileName = UploadFile(team);

            if (managerId.Equals(Guid.Empty) && !User.IsAdmin())
            {
                return RedirectToAction(nameof(ManagersController.Become), "Managers");
            }

            if (!this.teams.PlayerExists(team.PlayerId))
            {
                this.ModelState.AddModelError(nameof(team.PlayerId),
                    "Player does not exist.");
            }

            if (ModelState.IsValid)
            {
                team.Players = this.teams.AllTeams();

                return View(team);
            }

            if (!this.teams.IsByManager(id, managerId) && !User.IsAdmin())
            {
                return BadRequest();
            }

            var edited = this.teams.Edit(
                  id,
                  team.Name,
                  stringFileName,
                  team.WebSite,
                  team.LogoUrl,
                  team.HomeKit,
                  team.AwayKit,
                  team.NickName,
                  team.Description,
                  team.Address,
                  team.HeadCoach,
                  team.Champion,
                  team.Cup,
                  team.Win,
                  team.Defeats,
                  team.PlayerId,
                  this.User.IsAdmin());

            if (!edited)
            {
                return BadRequest();
            }

            TempData[GlobalMessageKey] = $"You Team was edited {(this.User.IsAdmin() ? string.Empty : " and is await for approval")}!";

            return RedirectToAction(nameof(Details), new { id, information = team.GetInformation() });
        }

        [HttpGet]
        public IActionResult Delete(Guid id)
        {
            if (id.Equals(Guid.Empty))
            {
                return NotFound();
            }

            var delete = this.teams.Delete(id);

            TempData[DangerMessageKey] = $"You Team was deleted!";

            return RedirectToAction(nameof(All));
        }
        private string UploadFile(TeamFormModel model)
        {
            string fileName = null;
            if (model.Image != null)
            {
                string uploadDir = Path.Combine(webHostEnvironment.WebRootPath, "img");
                fileName = Guid.NewGuid().ToString() + "-" + model.Image.FileName;
                string filePath = Path.Combine(uploadDir, fileName);

                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    model.Image.CopyTo(fileStream);
                }
            }

            return fileName;
        }
    }
}

Football/Controllers/UserController.cs
namespace Football.Controllers
{
    using Football.Core.Contracts;
    using Football.Infrastructure.Data.Identity;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    public class UserController : BaseController
    {
        private readonly RoleManager<IdentityRole> roleManager;

        private readonly UserManager<ApplicationUser> userManager;

        private readonly IUserService service;

        public UserController(
            RoleManager<IdentityRole> _roleManager,
            UserManager<ApplicationUser> _userManager, 
            IUserService _service)
        {
            this.roleManager = _roleManager;
            this.userManager = _userManager;
            this.service = _service;
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

Football/Views/Shared/_Layout.cshtml
@using Football.Infrastructure.Data
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="~/css/adminlte.min.css">
    <link rel="stylesheet" href="~/plugins/toastr/toastr.css" />

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    @await RenderSectionAsync("Head", false)
</head>
<body class="hold-transition sidebar-mini">
    <div class="wrapper">

        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    
                @if (User.IsInRole(DataConstants.Roles.RoleNameAdministrator) || (User.IsInRole(DataConstants.Roles.RoleNameManager)))
                {
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Positions" asp-action="Add">Добавяне позиция</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Players" asp-action="Add">Добавяне футболист</a>
                    </li>
                      <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Players" asp-action="All">Футболисти</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Teams" asp-action="Add">Добавяне отбор</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Teams" asp-action="All">Отбори</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Cities" asp-action="Add">Добавяне град</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Cities" asp-action="All">Градове</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Leagues" asp-action="Add">Добавяне лига</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Leagues" asp-action="All">Лиги</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Stadiums" asp-action="Add">Добавяне стадион</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Stadiums" asp-action="All">Стадиони</a>
                </li>
                }
                else
                {
                @*<li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Positions" asp-action="Add">Add Position</a>
                    </li>*@
                @* <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Players" asp-action="Add">Add Player</a>
                    </li>*@
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Players" asp-action="All">Футболисти</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Teams" asp-action="All">Отбори</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Cities" asp-action="All">Градове</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Leagues" asp-action="All">Лиги</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Stadiums" asp-action="All">Стадиони</a>
                </li>
                }
            </ul>
            
            <!-- Right navbar links -->
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })" method="post">
                        <i class="fas fa-door-open"></i>
                        <button type="submit" class="nav-link btn btn-link text-dark">Изход</button>
                    </form>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                        <i class="fas fa-expand-arrows-alt"></i>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="\" class="brand-link">
                <img src="~/img/Football-Logo.jpg" alt="Football Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
                <span class="brand-text font-weight-light">My Football</span>
            </a>
            <!-- Sidebar -->
            <div class="sidebar">
                <partial name="_LoginPartial" />

                <!-- Sidebar Menu -->
                <partial name="_MainMenu" />
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1 class="m-0">@ViewData["Title"]</h1>
                        </div><!-- /.col -->
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-left">
                               @* <li class="breadcrumb-item"><a href="#">Home</a></li>*@
                             @*   @if (User.IsAdmin())
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Players" asp-action="All">Administration Players</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Teams" asp-action="All">Administration Teams</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Cities" asp-action="All">Administration Cities</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Leagues" asp-action="All">Administration Leagues</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Stadiums" asp-action="All">Administration Stadiums</a>
                            </li>
                        }*@
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Teams" asp-action="All">All teams</a>*@
                                </ol>
                            <ol class="breadcrumb float-sm-right">
                                @*<li class="breadcrumb-item"><a href="#">Home</a></li>*@
                                @* <li class="breadcrumb-item active">Starter Page</li>*@
                                @if (User.IsInRole(DataConstants.Roles.RoleNameAdministrator))
                                {
                                     <a class="nav-link text-dark" asp-area="Admin" asp-controller="Teams" asp-action="All">Admin panel</a>
                                    @*<a class="nav-link text-dark" asp-area="Admin" asp-controller="User" asp-action="Manageusers">Admin Roles</a>*@
                                }
                                else if (User.IsInRole(DataConstants.Roles.RoleNameManager))
                                 {
                                    <a class="nav-link text-dark" asp-area="Manager" asp-controller="Home" asp-action="Index">Manager panel</a>
                                }
                                else
                                {
                                    <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">User</a>
                </li>
                                }
                            </ol>
                        </div><!-- /.col -->
                    </div><!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content-header -->
            <!-- Main content -->
            <div class="content">
                @if (TempData.ContainsKey(WebConstants.GlobalMessageKey))
                {
                    <div class="alert alert-success text-center" role="alert">
                       @TempData[WebConstants.GlobalMessageKey]
                    </div>
                }
                @if (TempData.ContainsKey(WebConstants.DangerMessageKey))
                {
                    <div class="alert alert-danger text-center" role="alert">
                        @TempData[WebConstants.DangerMessageKey]
                        </div>
                }
                <div class="container-fluid">
                    @RenderBody()
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <!-- Main Footer -->
        <footer class="main-footer">
             <a class="nav-link text-dark" asp-area="" asp-controller="Geo" asp-action="Details">Geo Location</a>
             <a class="nav-link text-dark" asp-area="" asp-controller="Footers" asp-action="Index">За нас</a>
             <a class="nav-link text-dark" asp-area="" asp-controller="Footers" asp-action="Contact">Контакти</a>
             <a class="nav-link text-dark" asp-area="" asp-controller="Footers" asp-action="TheTeam">Екип</a>
            <!-- To the right -->
            <div class="float-right d-none d-sm-inline">
               @* Anything you want*@
            </div>
            <!-- Default to the left -->
            <strong>Copyright &copy; 2014 - @DateTime.Now.Year<a href="/"> My Football</a>.</strong> @*All rights reserved.*@
        </footer>
    </div>
    <!-- ./wrapper -->
    <!-- REQUIRED SCRIPTS -->
    <!-- jQuery -->
    <script src="~/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/js/adminlte.min.js"></script>
    <script src="~/plugins/toastr/toastr.min.js"></script>
    <partial name="_UserMessages" />
    @await RenderSectionAsync("Scripts", false)
</body>
</html>

Football/Views/Shared/_LayoutOld.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Football</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Football.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Football</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Football - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Football/Views/Shared/_UserMessages.cshtml
@using Football.Core.Constants

 @if (ViewData[MessageConstant.ErrorMessage] != null)
    {
        <script>
            $(function(){
              toastr.error('@ViewData[MessageConstant.ErrorMessage]?.ToString()');
            });
        </script>
    }

    @if (ViewData[MessageConstant.WarningMessage] != null)
    {
        <script>
            $(function(){
              toastr.warning('@ViewData[MessageConstant.WarningMessage]?.ToString()');
            });
        </script>
    }

    @if (ViewData[MessageConstant.SuccessMessage] != null)
    {
        <script>
            $(function(){
              toastr.success('@ViewData[MessageConstant.SuccessMessage]?.ToString()');
            });
        </script>
    }