Football/Models/Players/AddPlayerFormModel.cs
namespace Football.Models.Players
{
    using System.ComponentModel.DataAnnotations;

    using static Football.Infrastructure.Data.DataConstants.Player;
    public class AddPlayerFormModel
    {
        [Display(Name = "First Name")]
        [Required]
        [StringLength(PlayerFirstNameMaxLength, MinimumLength = PlayerFirstNameMinLength, ErrorMessage = "Minimum: {2}, Maximum: {1}")]
        public string FirstName { get; init; }

        [Display(Name = "Middle Name")]
        [Required]
        [StringLength(PlayerMiddleNameMaxLength, MinimumLength = PlayerMiddleNameMinLength, ErrorMessage = "Minimum: {2}, Maximum: {1}")]
        public string MiddleName { get; init; }

        [Display(Name = "Last Name")]
        [Required]
        [StringLength(PlayerLastNameMaxLength, MinimumLength = PlayerLastNameMinLength, ErrorMessage = "Minimum: {2}, Maximum: {1}")]
        public string LastName { get; init; }

        [Display(Name = "Отбор")]
        [Required]
        [StringLength(PlayerTeamMaxLength, MinimumLength = PlayerTeamMinLength, ErrorMessage = "Minimum: {2}, Maximum: {1}")]
        public string Team { get; init; }

        [Range(PlayerAgeMinLength, PlayerAgeMaxLength)]
        public int Age { get; init; }

        public double Weight { get; init; }

        public double Height { get; init; }

        [Display(Name = "Image URL")]
        [Required]
        [Url]
        public string ImageUrl { get; init; }

        public int Goal { get; init; }

        [Display(Name = "Shirt Number")]
        [Range(PlayerShirtNumberMinValue, PlayerShirtNumberMaxValue, ErrorMessage = "Minimum: {1}, Maximum: {2}")]
        public byte ShirtNumber { get; init; }

        [Required]
        [StringLength(PlayerNationalityMaxLength, MinimumLength = PlayerNationalityMinLength, ErrorMessage = "Minimum: {2}, Maximum: {1}")]
        public string Nationality { get; init; }

        [Required()]
        [StringLength(int.MaxValue,
            MinimumLength = PlayerDescriptionMinLength,
            ErrorMessage = "The field Description must be a string with a minimum length of {2}.")]
        public string Description { get; init; }

        [Display(Name = "Position")]
        public Guid PositionId { get; init; }

        public IEnumerable<PlayerPositionViewModel> Positions { get; set; }
    }
}

Football/Models/Players/PlayerListingViewModel.cs
namespace Football.Models.Players
{
    public class PlayerListingViewModel
    {
        public Guid Id { get; set; }

        public string FirstName { get; set; }

        public string MiddleName { get; set; }

        public string LastName { get; set; }

        public string Team { get; set; }

        public int Age { get; set; }

        public string Image { get; set; }

        public string Nationality { get; set; }

        public string Position { get; set; }
    }
}

Football/Models/Players/PlayerPositionViewModel.cs
namespace Football.Models.Players
{
    public class PlayerPositionViewModel
    {
        public Guid Id { get; set; }

        public string Name { get; set; }
    }
}

Football/Areas/Admin/Controllers/PlayersController.cs
namespace Football.Areas.Admin.Controllers
{
    using Football.Core.Contracts;
    using Microsoft.AspNetCore.Mvc;

    public class PlayersController : BaseController
    {
        private readonly IPlayerService players;

        public PlayersController(IPlayerService _players)
        {
            this.players = _players;
        }

        public IActionResult All()
        {
            var players = this.players
                .All(publicOnly: false)
                .Players;

            return View(players);
        }

        public IActionResult ChangeVisibility(Guid id)
        {
            this.players.ChangeVisibility(id);

            return RedirectToAction(nameof(All));
        }
    }
}

Football/Controllers/PlayersController.cs
namespace Football.Controllers
{
    using Football.Core.Contracts;
    using Football.Core.Models.Players;
    using Football.Extensions;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    using static WebConstants;
    using static Football.Infrastructure.Data.DataConstants;
    public class PlayersController : Controller
    {
        private readonly IPlayerService players;
        private readonly IManagerService managers;

        private readonly IWebHostEnvironment webHostEnvironment;

        public PlayersController(
            IPlayerService _players,
            IManagerService _managers,
            IWebHostEnvironment _webHostEnvironment
            )
        {
            this.players = _players;
            this.managers = _managers;
            webHostEnvironment = _webHostEnvironment;
        }

        public IActionResult All([FromQuery]
            AllPlayersQueryModel query)
        {
            var queryResult = this.players.All(
                query.Team,
                query.SearchTerm,
                query.Sorting,
                query.CurrentPage,
                AllPlayersQueryModel.PlayersPerPage);

            var playerTeams = this.players.AllTeams();

            query.Teams = playerTeams;
            query.TotalPlayers = queryResult.TotalPlayers;
            query.Players = queryResult.Players;

            return View(query);
        }

        public IActionResult Details(Guid id, string information)
        {
            var player = this.players.Details(id);

            if (information != player.GetInformation())
            {
                return BadRequest();
            }

            return View(player);
        }

        [Authorize]
        public IActionResult Mine()
        {
            var myPlayers = this.players.ByUser(this.User.Id());

            return View(myPlayers);
        }

        [Authorize]
        public IActionResult Add()
        {
            //TODO
            if (!this.managers.IsManager(this.User.Id()))
            {
                return RedirectToAction(nameof(ManagersController.Become), "Managers");
            }

            return View(new PlayerFormModel
            {
                Positions = this.players.AllPositions()
            });
        }

        [HttpPost]
        [Authorize]
        public IActionResult Add(PlayerFormModel player)
        {
            var managerId = this.managers.IdByUser(this.User.Id());

            if (managerId.Equals(Guid.Empty))
            {
                return RedirectToAction(nameof(ManagersController.Become), "Managers");
            }

            if (!this.players.PositionExists(player.PositionId))
            {
                this.ModelState.AddModelError(nameof(player.PositionId), "Position does not exist.");
            }

            if (ModelState.IsValid)
            {
                player.Positions = this.players.AllPositions();

                return View(player);
            }

            string stringFileName = UploadFile(player);

            var playerId = this.players.Create(
                player.FirstName,
                player.MiddleName,
                player.LastName,
                player.Team,
                player.Age,
                player.Weight,
                player.Height,
                stringFileName,
                player.Goal,
                player.ShirtNumber,
                player.Nationality,
                player.Description,
                player.PositionId,
                managerId);

            TempData[GlobalMessageKey] = "You Player was added and is awaiting for approval!";

            return RedirectToAction(nameof(Details), new { id = playerId, information = player.GetInformation() });
        }

        [Authorize]
        public IActionResult Edit(Guid id)
        {
            var userId = this.User.Id();

            if (!this.managers.IsManager(userId) && !User.IsAdmin())
            {
                return RedirectToAction(nameof(ManagersController.Become), "Managers");
            }

            var player = this.players.Details(id);

            if (player.UserId != userId && !User.IsInRole(Roles.RoleNameAdministrator))
            {
                return Unauthorized();
            }

            return View(new PlayerFormModel
            {
                FirstName = player.FirstName,
                MiddleName = player.MiddleName,
                LastName = player.LastName,
                Team = player.Team,
                Age = player.Age,
                Weight = player.Weight,
                Height = player.Height,
                //Image = player.Image,
                Goal = player.Goal,
                ShirtNumber = player.ShirtNumber,
                Nationality = player.Nationality,
                Description = player.Description,
                PositionId = player.PositionId,
                Positions = this.players.AllPositions()
            });
        }

        [HttpPost]
        [Authorize]
        public IActionResult Edit(Guid id, PlayerFormModel player)
        {
            var managerId = this.managers.IdByUser(this.User.Id());

            string stringFileName = UploadFile(player);

            if (managerId.Equals(Guid.Empty) && !User.IsAdmin())
            {
                return RedirectToAction(nameof(ManagersController.Become), "Managers");
            }

            if (!this.players.PositionExists(player.PositionId))
            {
                this.ModelState.AddModelError(nameof(player.PositionId), "Position does not exist.");
            }

            if (ModelState.IsValid)
            {
                player.Positions = this.players.AllPositions();

                return View(player);
            }

            //if (!this.players.IsByManager(id, managerId) && !User.IsAdmin())
            //{
            //    return BadRequest();
            //}

            this.players.Edit(
                id,
                player.FirstName,
                player.MiddleName,
                player.LastName,
                player.Team,
                player.Age,
                player.Weight,
                player.Height,
                stringFileName,
                player.Goal,
                player.ShirtNumber,
                player.Nationality,
                player.Description,
                player.PositionId,
                this.User.IsAdmin());

            TempData[GlobalMessageKey] = $"You Team was edited {(this.User.IsAdmin() ? string.Empty : " and is await for approval!")}";

            return RedirectToAction(nameof(Details), new { id, information = player.GetInformation() });
        }


        [HttpGet]
        public IActionResult Delete(Guid id)
        {
            if (id.Equals(Guid.Empty))
            {
                return NotFound();
            }

            var delete = this.players.Delete(id);

            TempData[DangerMessageKey] = $"You Player was deleted!";

            return RedirectToAction(nameof(All));
        }
        private string UploadFile(PlayerFormModel model)
        {
            string fileName = null;
            if (model.Image != null)
            {
                string uploadDir = Path.Combine(webHostEnvironment.WebRootPath, "img");
                fileName = Guid.NewGuid().ToString() + "-" + model.Image.FileName;
                string filePath = Path.Combine(uploadDir, fileName);

                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    model.Image.CopyTo(fileStream);
                }
            }

            return fileName;
        }
    }
}

Football/Views/Players/Add.cshtml
@model PlayerFormModel

@{
    ViewData["Title"] = "Добавяне на футболист";
}

@*<partial name="_PlayerFormPartial" model="@Model" />*@
<partial name="_PlayerFormPartial" model="@Model"/>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Football/Views/Players/All.cshtml
@model AllPlayersQueryModel

@{
    ViewData["Title"] = "Всички футболисти";
}

<form method="get">
    <div class="row">
        <div class="form-group col-md-4">
            <div class="form-group">
                <label asp-for="Team"></label>
                <select asp-for="Team" class="form-control">
                    <option value="">Всички</option>

                    @foreach (var team in Model.Teams)
                    {
                        <option value="@team">@team</option>
                    }
                </select>
            </div>
        </div>

        <div class="form-group col-md-4">
            <label asp-for="SearchTerm"></label>
            <input asp-for="SearchTerm" class="form-control" placeholder="Иван Петков Колев...">
        </div>

        <div class="form-group col-md-4">
            <div class="form-group">
                <label asp-for="Sorting"></label>
                <select asp-for="Sorting" class="form-control">
                    <option value="0" selected>Име Презиме Фамилия</option>
                    <option value="1" selected>Отбор</option>
                    <option value="2" selected>Позиция</option>
                    <option value="3" selected>Описание</option>
                </select>
            </div>
        </div>
    </div>
</form>

@{
    var previousPage = Model.CurrentPage - 1;
    if (previousPage < 1)
    {
        previousPage = 1;
    }

    var maxPage = Math.Ceiling((double)Model.TotalPlayers / AllPlayersQueryModel.PlayersPerPage);
}

<div class="row mb-5">
    <div class="col-md-6">
        <a class="btn btn-primary @(Model.CurrentPage == 1 ? "disabled" : string.Empty)"
           asp-controller="Players"
           asp-action="All"
           asp-route-currentPage="@previousPage"
           asp-route-team="@Model.Team"
           asp-route-searchTerm="@Model.SearchTerm"
           asp-route-sorting="@((int)Model.Sorting)"><<</a>
    </div>
    <div class="col-md-6">
        <a class="btn btn-primary float-right @(Model.CurrentPage == maxPage ? "disabled" : string.Empty)"
           asp-controller="Players"
           asp-action="All"
           asp-route-currentPage="@(Model.CurrentPage + 1)"
           asp-route-team="@Model.Team"
           asp-route-searchTerm="@Model.SearchTerm"
           asp-route-sorting="@((int)Model.Sorting)">>></a>
    </div>
    <br />
    <br />

    @if (!Model.Players.Any())
    {
      <h2 class="text-center">Няма намерени играчи по зададените критерии!</h2>
}

<partial name="_PlayersPartial" model="@Model.Players" />

Football/Views/Players/Details.cshtml
@model PlayerDetailsServiceModel

@{
    ViewData["Title"] = "Футболист";
}

<div class="col-md-6 offset-3">

    <img src="~/img/@Model.Image" width="300" height="200>

"></h2>

    @*<h2><a href="#" class="text-primary">Primary link</a></h2>*@
</div>
<br />


<div class="col-md-6 offset-3">

    <td><h3></h3>Име:</td>
              <h2 class="list-group-item"> @Model.FirstName</h2>
    <td><h3></h3>Презиме:</td>
                <h2 class="list-group-item"> @Model.MiddleName</h2>
    <td><h3></h3>Фамилия:</td>
                <h2 class="list-group-item"> @Model.LastName</h2>
    <td><h3></h3>Отбор:</td>
                <h2 class="list-group-item"> @Model.Team</h2>
    <td><h3></h3>Години:</td>
                <h2 class="list-group-item"> @Model.Age</h2>
    <td><h3></h3>Килограми:</td>
                <h2 class="list-group-item"> @Model.Weight</h2>
    <td><h3></h3>Височина:</td>
                <h2 class="list-group-item"> @Model.Height</h2>
    <td><h3></h3>Голове:</td>
                <h2 class="list-group-item"> @Model.Goal</h2>
    <td><h3></h3>Номер:</td>
                <h2 class="list-group-item"> @Model.ShirtNumber</h2>
    <td><h3></h3>Националност:</td>
                <h2 class="list-group-item"> @Model.Nationality</h2>
    <td><h3></h3>Описание:</td>
                <h2 class="list-group-item"> @Model.Description</h2>
    <td><h3></h3>Позиция:</td>
                 <h2 class="list-group-item"> @Model.PositionName</h2>


</div>

Football/Views/Players/Edit.cshtml
@model PlayerFormModel

@{
    ViewBag.Title = "Редактиране на футболист";
}

<partial name="_PlayerFormPartial" model="@Model" />

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Football/Views/Players/Mine.cshtml
@model IEnumerable<PlayerServiceModel>

@{
    ViewBag.Title = "Моите футболисти";
    ViewBag.AllowPlayerEdit = true;
}

@if (!Model.Any())
{
    <h2 class="text-center">Все още нямате играчи!</h2>
}

 <partial name="_PlayersPartial" model="@Model" />

Football/Views/Players/_PlayerFormPartial.cshtml
@model PlayerFormModel

<div class="container">
    <div class="row">
        <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
            <h2 class="heading-margin text-center">@ViewBag.Title</h2>
              <form method="post" enctype="multipart/form-data">
                <div class="form-group">
                    <label asp-for="FirstName"></label>
                    <input asp-for="FirstName" class="form-control" placeholder="Христо, Димитър, и т.н...">
                    <span asp-validation-for="FirstName" class="small text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="MiddleName"></label>
                    <input asp-for="MiddleName" class="form-control" placeholder="Стоичков, Димитров, и т.н...">
                     <span asp-validation-for="MiddleName" class="small text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="LastName"></label>
                    <input asp-for="LastName" class="form-control" placeholder="Стоичков, Димитров, и т.н...">
                     <span asp-validation-for="LastName" class="small text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Team"></label>
                    <input asp-for="Team" class="form-control" placeholder="Левски, Берое, ЦСКА и т.н....">
                     <span asp-validation-for="Team" class="small text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Age"></label>
                    <input asp-for="Age" class="form-control" placeholder="23">
                   <span asp-validation-for="Age" class="small text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Weight"></label>
                    <input asp-for="Weight" class="form-control" placeholder="66">
                </div>

                <div class="form-group">
                    <label asp-for="Height"></label>
                    <input asp-for="Height" class="form-control" placeholder="1.84">
                </div>

                <div class="form-group">
                    <label asp-for="Image"></label>
                    <input asp-for="Image" class="form-control">
                     <span asp-validation-for="Image" class="small text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Goal"></label>
                    <input asp-for="Goal" class="form-control">
                </div>

                <div class="form-group">
                    <label asp-for="ShirtNumber"></label>
                    <input asp-for="ShirtNumber" class="form-control" placeholder="От 1 до 99">
                     <span asp-validation-for="ShirtNumber" class="small text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Nationality"></label>
                    <input asp-for="Nationality" class="form-control" placeholder="Българин, Американец и т.н....">
                     <span asp-validation-for="Nationality" class="small text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Description"></label>
                    <textarea asp-for="Description" rows="4" class="form-control" placeholder="Това е добър футболист."></textarea>
                     <span asp-validation-for="Description" class="small text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PositionId"></label>
    <select asp-for="PositionId" class="form-control"> 
                    @foreach (var position in Model.Positions)
                    {
              <option value="@position.Id">@position.Name</option>
                    }
    </select>
    <span asp-validation-for="PositionId" class="small text-danger"></span>
 </div>
            <br />
            <input class="btn btn-primary" type="submit" value="Save" />
        </form>
            <br />
    </div>
</div>
</div>

Football/Views/Players/_PlayersPartial.cshtml
@model IEnumerable<PlayerServiceModel>

<div class="row">

    @foreach (var player in Model)
    {
        <div class="col-md-4">
            <div class="card mb-3">
                <img src="~/img/@player.Image" alt=" @player.FirstName @player.MiddleName @player.LastName - @player.Age @player.Nationality @player.Team (@player.PositionName)" width="200" height="300">
                <div class="card-body text-center">
                    <h5 class="card-title text-center">(№@player.ShirtNumber) @player.FirstName  @player.MiddleName @player.LastName отбор - @player.Team @player.PositionName (@player.Age г.)</h5>
                    <br />
                    <a asp-controller="Players" asp-action="Details" asp-route-id=@player.Id  asp-route-information="@player.GetInformation()" class="btn btn-primary">View</a>
                @if (ViewBag.AllowPlayerEdit == true || User.IsAdmin())
                    {
                        <a asp-controller="Players" asp-action="Edit" asp-route-id="@player.Id" class="btn btn-warning">Edit</a>
                        <a asp-controller="Players" asp-action="Delete" asp-route-id="@player.Id" class="btn btn-danger">Delete</a>
                    }
                </div>
            </div>
        </div>
    }
</div>